# 알파인 베이스 이미지 사용
FROM alpine:latest

# 기본 패키지 설치
RUN apk add --no-cache \
    openjdk17-jdk \
    curl \
    bash \
    git

# Maven 3.8.1 다운로드 및 설치
RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz | tar -xz -C /opt && \
    ln -s /opt/apache-maven-3.8.1 /opt/maven

# Maven 환경 변수 설정
ENV MAVEN_HOME=/opt/maven
ENV PATH=$MAVEN_HOME/bin:$PATH

# Java 환경 변수 설정
ENV JAVA_HOME=/usr/lib/jvm/default-jvm

# 기본적으로 Java 및 Maven 버전 확인
RUN java -version && mvn -version

# 작업 디렉토리 설정
WORKDIR /app

# 컨테이너가 시작되면 /bin/sh 실행
CMD ["/bin/sh"]

