# 알파인 베이스 이미지 사용
FROM alpine:latest

# 패키지 설치, Maven 설치 및 환경 변수 설정, 캐시 제거
RUN apk add --no-cache \
    openjdk17-jdk \
    curl \
    bash && \
    curl -fsSL https://archive.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz -o /tmp/apache-maven-3.8.1-bin.tar.gz && \
    tar -xz -C /opt -f /tmp/apache-maven-3.8.1-bin.tar.gz && \
    ln -s /opt/apache-maven-3.8.1 /opt/maven && \
    rm /tmp/apache-maven-3.8.1-bin.tar.gz && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/* && \
    export JAVA_HOME=/usr/lib/jvm/default-jvm && \
    export MAVEN_HOME=/opt/maven && \
    export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH && \
    java -version && mvn -version

# 작업 디렉토리 설정
WORKDIR /app

# 기본적으로 bash를 실행하도록 설정
CMD ["bash"]

